version: "3.8"
 
services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-dock-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employee_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    networks:
      - spring-net
 
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-container
    ports:
      - "8900:8080"
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/employee_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - spring-net
 
networks:
  spring-net: